version: "3.9"

services:
  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongodb
      - rabbitmq

  job-service:
    build: ./job-service
    container_name: job-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - ./job-service/.env
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: user_service
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data:
